# Generated by Django 5.2.6 on 2025-09-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
