# Generated by Django 5.2.6 on 2025-09-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
